# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-FindWindow
version:      0.03
version_from: lib/Win32/FindWindow.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Test::More:                    0
    Test::Perl::Critic:            0
    Win32::API:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
